### ISSUE TITLE
Logging framework usage

### ISSUE THREAD

**Issue by ghost** [OrionInnovationTRTech/laborant#4]
Fill your operations with meaningful logging operations in order to help debug/understand the application for the other developers.
You can use a logging framework like Log4j, Slf4j, JUL....

**Comment by kemalyildirim** [comment]
Add lombok library in the project for logging https://projectlombok.org/features/log

instead of `System.out.println` use logging framework.

- [x] Research on logging with Java and different logging frameworks
- [x] Choose a logging framework and add it to the dependencies.
- [x] Declare loggers with lombok logging annotations.
- [x] For now, logging to the console is enough.
